#
# Build
#

set build_components {
	core init
	drivers/timer
	drivers/rtc
	server/ram_fs
	test/libart/art_runtime
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="500"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="rtc_drv">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Rtc"/> </provides>
	</start>

	<start name="ram_fs">
		<resource name="RAM" quantum="128M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<default-policy root="/" writeable="true" />
		</config>
	</start>

	<start name="art_runtime_test">
		<resource name="RAM" quantum="512MB"/>
		<config>
			<vfs>
				<dir name="tmp"> <fs/> </dir>
				<dir name="dev">
					<log/>
					<rtc/>
				</dir>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" />
		</config>
	</start>
</config>}

#
# Boot image
#

# generic modules
set boot_modules {
	core init ld.lib.so
	timer ram_fs
	libc.lib.so libm.lib.so
	posix.lib.so pthread.lib.so stdcxx.lib.so
	lwip.lib.so
	liblog.lib.so libbase.lib.so libutils.lib.so libcutils.lib.so
	libfakeatomic.lib.so libbacktrace.lib.so icu.lib.so
	libart.lib.so liblz4.lib.so libnativebridge.lib.so
	libnativehelper.lib.so libnativeloader.lib.so
	libutils.lib.so zlib.lib.so libziparchive.lib.so
	sigchainlib.lib.so
	rtc_drv
	art_runtime_test
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 1024 -nographic "
run_genode_until {.*child "art_runtime_test" exited with exit value 0} 100
