#
# Build
#

set build_components {
	core init
	drivers/timer
	drivers/rtc
	lib/vfs/lxip
	server/ram_fs
	server/nic_loopback
	test/libcutils
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="500"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="rtc_drv">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Rtc"/> </provides>
	</start>

	<start name="ram_fs">
		<resource name="RAM" quantum="128M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<default-policy root="/" writeable="true" />
		</config>
	</start>

    <start name="nic_loopback">
        <resource name="RAM" quantum="1M"/>
        <provides><service name="Nic"/></provides>
    </start>

	<start name="libcutils_test">
		<resource name="RAM" quantum="128M"/>
		<config>
			<vfs>
				<dir name="tmp"> <fs/> </dir>
				<dir name="socket">
					<lxip/>
				</dir>
				<dir name="dev"> <log/> <rtc/> </dir>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" socket="/socket" ip_addr="192.168.100.1" netmask="255.255.255.0" gateway="192.168.100.254"/>
		</config>
	</start>
</config>}

#
# Boot image
#

# generic modules
set boot_modules {
	core init ld.lib.so
	timer ram_fs
	libc.lib.so libm.lib.so
	posix.lib.so pthread.lib.so stdcxx.lib.so
	libc_resolv.lib.so
	vfs_lxip.lib.so lxip.lib.so
	liblog.lib.so libbase.lib.so libcutils.lib.so
	rtc_drv
	nic_loopback
	libcutils_test
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 512 -nographic "
run_genode_until {.*child "libcutils_test" exited with exit value 0} 100
