# RTC test

build {
    core init
    test/concurrency/mutex
    drivers/timer
}

create_boot_directory

install_config {
<config prio_levels="2" verbose="yes">

    <parent-provides>
        <service name="ROM"/>
        <service name="IRQ"/>
        <service name="IO_MEM"/>
        <service name="IO_PORT"/>
        <service name="PD"/>
        <service name="RM"/>
        <service name="CPU"/>
        <service name="LOG"/>
    </parent-provides>
    <default-route>
        <any-service> <parent/> <any-child/> </any-service>
    </default-route>
    <default caps="100"/>

    <start name="timer">
        <resource name="RAM" quantum="1M"/>
        <provides>
            <service name="Timer"/>
        </provides>
    </start>

    <start name="test-concurrency-mutex" priority="-1">
        <resource name="RAM" quantum="4M"/>
    </start>

</config>
}

build_boot_image {
    core ld.lib.so init cxxthreads.lib.so
    libc.lib.so libm.lib.so stdcxx.lib.so
    timer test-concurrency-mutex
}

append qemu_args " -nographic  "

run_genode_until "Mutex OK" 10
