#!/bin/sh

TESTS=" \
	run/test/libbase \
	run/test/libnativehelper \
	run/test/liblog \
	run/test/libnativebridge/PreInitializeNativeBridgeFail1 \
	run/test/libnativebridge/ReSetupNativeBridge \
	run/test/libnativebridge/CodeCacheExists \
	run/test/libnativebridge/PreInitializeNativeBridgeFail2 \
	run/test/libnativebridge/PreInitializeNativeBridge \
	run/test/libnativebridge/CodeCacheCreate \
	run/test/libnativebridge/CodeCacheStatFail \
	run/test/libnativebridge/NativeBridge3CreateNamespace \
	run/test/libnativebridge/ValidNameNativeBridge \
	run/test/libnativebridge/NativeBridge3LoadLibraryExt \
	run/test/libnativebridge/NeedsNativeBridge \
	run/test/libnativebridge/NativeBridge3InitAnonymousNamespace \
	run/test/libnativebridge/NativeBridge3IsPathSupported \
	run/test/libnativebridge/NativeBridge3UnloadLibrary \
	run/test/libnativebridge/NativeBridge3GetError \
	run/test/libnativebridge/InvalidCharsNativeBridge \
	run/test/libnativebridge/UnavailableNativeBridge \
	run/test/libnativebridge/CompleteFlow \
	run/test/libnativebridge/NativeBridgeVersion \
	run/mfe/symlink_eloop_not_detected \
	run/mfe/realpath_invalid \
	run/mfe/symlink_integrity \
	run/mfe/symlink_length \
	run/mfe/symlink_deadlock \
	"

make ${TESTS}
