#!/bin/bash

IGNORE="
	-e run/dalvikvm
	-e run/mfe/getsockopt_so_error
	-e run/mfe/writev_socket_short
	-e run/mfe/sock_receive_timeout
	-e run/mfe/difftime_subsecond
	"

BASEDIR=$(dirname $0)/../run
for T in $(find ${BASEDIR} -name '*.run' | grep -v ${IGNORE})
do
test
	TEST=${T%%.run}
	TESTS="${TESTS} run/${TEST##${BASEDIR}}"
done

echo "Ignoring: ${IGNORE}" | sed -e 's/-e //g'

make ${TESTS}
