#!/usr/bin/env python3

import sys
import pprint
import argparse
from pyparsing import *

def make_error (message):
    print ("$(error " + message + ")")

class QueryParser:

    def queryAction (self, string, location, tokens):
        self.target = tokens[0]

    def __init__ (self, data, query):

        self.target = None
        self.data   = ""

        colon       = Literal (':')
        name        = Word (alphanums + "_")

        self.query = name + colon
        self.query.setParseAction (self.queryAction)

        self.query.parseString (query[0])

        for d in data:
            for target in d.keys():
                if target == self.target:
                    self.data += ("SRCS = " + "".join (d[target]['srcs']))

class SoongParser:

    def stringListAction (self, string, location, tokens):
        last = -2 if tokens[-2] == ',' else -1
        return [tokens[1:last]]

    def stringListJoinAction (self, string, location, tokens):
        result = tokens[0]
        if len(tokens) == 2:
            result += tokens[1]
        return result

    def dictelemAction (self, string, location, tokens):
        return {tokens[0]: tokens[2:]}

    def variableAction (self, string, location, tokens):
        self.variables[tokens[0]] = [tokens[2:]]

    def rnameAction (self, string, location, tokens):
        varname = tokens[0]
        if not varname in self.variables:
            raise Exeception ("Error: %s: Variable '%s' no found" % (self.file, varname))
        return self.variables[varname]

    def dictionaryAction (self, string, location, tokens):
        result = {}
        last = -2 if tokens[-2] == ',' else -1
        for token in tokens[1:last]:
            result.update (token)
        return result

    def soongAction (self, string, location, tokens):
        self.data = tokens

    def __init__ (self, dir):

        self.variables = {}
        self.file = None
        self.data = None

        comma   = Literal (',')
        colon   = Literal (':')
        equals  = Literal ('=')
        true    = Literal ('true').setParseAction (lambda v : True)
        false   = Literal ('false').setParseAction (lambda v : False)
        name    = Word (alphanums + "_")

        # Variable reference
        rname = Word (alphanums + "_")
        rname.setParseAction (self.rnameAction)

        # Boolean literal true/false
        boolean     = true | false

        # String
        string     = QuotedString ('"', escChar='\\')
        stringjoin = delimitedList (string, delim='+')

        # List of strings
        stringlist     = Literal ("[") + Optional (delimitedList (stringjoin)) + Optional (comma) + Literal ("]")
        stringlist.setParseAction (self.stringListAction)

        stringlistjoin = delimitedList (stringlist|rname, delim='+')
        stringlistjoin.setParseAction (self.stringListJoinAction)

        # Dictionary
        dictelem    = Forward()
        dictelem.setParseAction (self.dictelemAction)

        dictionary  = Literal ("{") + Optional (delimitedList (dictelem)) + Optional (comma) + Literal ("}")
        dictionary.setParseAction (self.dictionaryAction)

        # Element
        element   = boolean | stringlistjoin | rname | stringjoin | dictionary

        dictelem << name + (colon|equals) + element

        block = name + element
        block.setParseAction (lambda s, l, t: {t[0]: t[1]})

        variable = name + Literal ("=") + element
        variable.setParseAction (self.variableAction)

        extension   = name + Literal ("+=") + element

        self.grammar = ZeroOrMore (block | variable.suppress() | extension) + StringEnd()
        self.grammar.setParseAction (self.soongAction)

        # C and C++ style comments
        self.grammar.ignore (cppStyleComment | cStyleComment)
        try:
            self.grammar.parseFile (dir + "/Android.bp")
        except Exception as e:
            make_error (str (e))
            raise

    def query (self, query):
        q = QueryParser (self.data, query)

parser = argparse.ArgumentParser (description = 'Translate soong file to make statements')
parser.add_argument ('dir')
parser.add_argument ('query', nargs=argparse.REMAINDER)
args = parser.parse_args()

try:
    soong = SoongParser (args.dir)
    soong.query (args.query)
except ParseException as e:
    print ("Parse error in %s: %s" % (arg, str(e)))
except Exception:
    pass
