#!/usr/bin/env python3

import sys
import argparse
import unittest

class Soong:

    def __init__ (self, infile):
        self._data = {}
        self._data[infile] = []

    def data (self):
        return self._data

class TestSoong (unittest.TestCase):

    def setUp (self):
        self.testdir = "tests/soong2mk"

    def test_empty_input (self):
        infile = self.testdir + "001_empty_file.bp"
        data = Soong (infile).data()
        # Expect empty result data for empty file
        self.assertFalse (data[infile])

if __name__ == "__main__":
    suite = unittest.TestLoader().loadTestsFromTestCase(TestSoong)
    unittest.TextTestRunner().run(suite)
